[WD-121971] Model Performance
waterdipai/waterdip pull request #91
Opened 2023-02-01 14:25 UTC by WeryZebra-Yue

2023-02-03 15:29 UTC, Godzilla5111 requested changes

2023-02-03 15:29 UTC, Godzilla5111 commented on waterdip/__main__.py
> +        reload=True,
Not needed.

2023-02-03 15:57 UTC, subhankarb approved these changes

2023-02-03 15:57 UTC, subhankarb commented on waterdip/server/services/metrics_service.py
> +        dataset_id = self._dataset_service.find_dataset_by_id(
@WeryZebra-Yue Use find event_dataset method

2023-02-03 15:57 UTC, subhankarb commented on tests/server/services/test_metric_service.py
> +    @classmethod
@WeryZebra-Yue  One test to check the error if positive class not found.

2023-02-06 15:38 UTC, Godzilla5111 approved these changes

2023-02-06 15:39 UTC, merged